In [2]:
import numpy as np

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [5]:
x.ndim

1

In [6]:
X.ndim

2

In [7]:
x.shape

(10,)

In [8]:
X.shape

(3, 5)

In [9]:
x.size

10

In [10]:
X.size

15

### numpy.array的数据访问

In [11]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x[0]

0

In [13]:
x[-1]

9

In [14]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
X[0][0]

0

In [16]:
X[2,2]

12

In [17]:
x[0:5]

array([0, 1, 2, 3, 4])

In [18]:
x[:5]

array([0, 1, 2, 3, 4])

In [19]:
x[5:]

array([5, 6, 7, 8, 9])

In [20]:
x[::2]

array([0, 2, 4, 6, 8])

In [21]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [22]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [24]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [27]:
X[0]

array([0, 1, 2, 3, 4])

In [28]:
X[0,:]

array([0, 1, 2, 3, 4])

In [29]:
X[0,:].ndim

1

In [30]:
X[:,0]

array([ 0,  5, 10])

In [31]:
X[:,0].ndim

1

In [32]:
subX = X[:2,:3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [33]:
subX[0,0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [34]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [35]:
X[0,0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [37]:
subX = X[:2,:3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [38]:
subX[0,0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [39]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [40]:
x.shape

(10,)

In [41]:
x.ndim

1

In [42]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
A = x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
B = x.reshape(1,10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [47]:
B.shape

(1, 10)

In [48]:
B.ndim

2

In [49]:
x.shape

(10,)

In [50]:
x.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [51]:
x.reshape(-1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [52]:
x.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 合并操作

In [53]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [54]:
x

array([1, 2, 3])

In [55]:
y

array([3, 2, 1])

In [56]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [57]:
z = np.array([666,666,666])

In [58]:
np.concatenate([x , y ,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [59]:
A = np.array([[1, 2 ,3],
             [4, 5, 6]])

In [60]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [61]:
np.concatenate([A , A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [62]:
np.concatenate([A, z])

ValueError: all the input arrays must have same number of dimensions

In [63]:
np.concatenate([A, z.reshape(1,-1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [64]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
A2 = np.concatenate([A, z.reshape(1,-1)])

In [66]:
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [67]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [68]:
B = np.full((2,2), 100)

In [69]:
B

array([[100, 100],
       [100, 100]])

In [70]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 分割

In [71]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
x1, x2, x3 = np.split(x,[3, 7])

In [73]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
x1

array([0, 1, 2])

In [75]:
x2

array([3, 4, 5, 6])

In [76]:
x3

array([7, 8, 9])

In [77]:
x1, x2 = np.split(x, [5])

In [78]:
x1

array([0, 1, 2, 3, 4])

In [79]:
x2

array([5, 6, 7, 8, 9])

In [80]:
A = np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
A1, A2 = np.split(A,[2])

In [82]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [83]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
A1, A2 = np.split(A,[2], axis = 1)

In [85]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [86]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [87]:
upper, lower = np.vsplit(A, [2])

In [88]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [89]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
left, right = np.hsplit(A,[2])

In [91]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [92]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [93]:
data = np.arange(16).reshape((4,4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
X, y = np.hsplit(data,[-1])

In [95]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [96]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [97]:
y[:,0]

array([ 3,  7, 11, 15])

## numpy.array中的运算

#### 给定一个向量，让向量中每一个数乘以2
a = （0，1，2）
a*2 = （0，2，4)

In [98]:
n = 10
L = [i for i in range(n)]

In [99]:
2*L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [100]:
A = []
for e in L:
    A.append(2*e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [101]:
n = 1000000
L = [i for i in range(n)]

In [102]:
%%time
A = []
for e in L:
    A.append(2*e)

Wall time: 279 ms


In [103]:
%%time
A = [2*e for e in L]

Wall time: 147 ms


In [104]:
L = np.arange(n)

In [105]:
%%time
A = np.array(2*e for e in L)

Wall time: 19 ms


In [106]:
%%time
A = 2 * L

Wall time: 1.98 ms


In [107]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [108]:
n = 10
L = np.arange(n)
2 * L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Universal Function

In [109]:
X = np.arange(1,16).reshape((3, 5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [110]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [111]:
X - 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [112]:
X * 2 

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [113]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [114]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [115]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [116]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [117]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [118]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [119]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [120]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [121]:
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [122]:
3 ** X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [123]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [124]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [125]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

## 矩阵运算

In [126]:
A = np.arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [127]:
B = np.full((2,2), 10)
B

array([[10, 10],
       [10, 10]])

In [128]:
A + B

array([[10, 11],
       [12, 13]])

In [129]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [130]:
A * B

array([[ 0, 10],
       [20, 30]])

In [131]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [132]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [133]:
A 

array([[0, 1],
       [2, 3]])

In [134]:
A.T

array([[0, 2],
       [1, 3]])

In [135]:
c = np.full((3, 3), 666)

## 向量和矩阵的运算

In [136]:
v = np.array([1, 2])

In [137]:
A

array([[0, 1],
       [2, 3]])

In [138]:
v + A

array([[1, 3],
       [3, 5]])

In [139]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [140]:
np.vstack([v] * A.shape[0]) + A

array([[1, 3],
       [3, 5]])

In [141]:
np.tile(v, (2, 1))

array([[1, 2],
       [1, 2]])

In [142]:
v

array([1, 2])

In [143]:
A

array([[0, 1],
       [2, 3]])

In [144]:
v * A

array([[0, 2],
       [2, 6]])

In [145]:
v.dot(A)

array([4, 7])

In [146]:
A.dot(v)

array([2, 8])

## 矩阵的逆

In [147]:
A

array([[0, 1],
       [2, 3]])

In [148]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [149]:
invA= np.linalg.inv(A)

In [150]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [151]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [152]:
np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

In [153]:
pinvX = np.linalg.pinv(X)

In [154]:
pinvX

array([[-2.46666667e-01, -6.66666667e-02,  1.13333333e-01],
       [-1.33333333e-01, -3.33333333e-02,  6.66666667e-02],
       [-2.00000000e-02, -2.51534904e-17,  2.00000000e-02],
       [ 9.33333333e-02,  3.33333333e-02, -2.66666667e-02],
       [ 2.06666667e-01,  6.66666667e-02, -7.33333333e-02]])

In [155]:
pinvX.shape

(5, 3)

In [156]:
X.dot(pinvX)

array([[ 0.83333333,  0.33333333, -0.16666667],
       [ 0.33333333,  0.33333333,  0.33333333],
       [-0.16666667,  0.33333333,  0.83333333]])

## 聚合操作

In [157]:
L = np.random.random(100)

In [158]:
L

array([0.04699514, 0.06115139, 0.20324168, 0.78291056, 0.32073285,
       0.48911264, 0.38661926, 0.20658481, 0.52407259, 0.604645  ,
       0.46089916, 0.98847888, 0.48607252, 0.89474853, 0.85364995,
       0.75237402, 0.78254531, 0.27474794, 0.2635556 , 0.3460091 ,
       0.65900918, 0.15144333, 0.35841145, 0.79071245, 0.06897168,
       0.69364608, 0.31204771, 0.35735633, 0.15853265, 0.61315118,
       0.12893873, 0.80548718, 0.47260198, 0.22276906, 0.24523511,
       0.31646316, 0.85268722, 0.25366575, 0.95360814, 0.67855718,
       0.39854823, 0.68422002, 0.07402506, 0.3694639 , 0.16420102,
       0.56236938, 0.79022582, 0.56177538, 0.43925135, 0.53896523,
       0.171434  , 0.90761894, 0.25870577, 0.77053736, 0.43020629,
       0.11510797, 0.6114777 , 0.78194097, 0.98476196, 0.19534522,
       0.92579696, 0.98587958, 0.2166795 , 0.85388219, 0.70235069,
       0.27973911, 0.3300407 , 0.05368135, 0.71107072, 0.42446067,
       0.32077573, 0.03622009, 0.01005076, 0.005113  , 0.31908

In [159]:
sum(L)

47.958919717437404

In [160]:
np.sum(L)

47.95891971743741

In [161]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

185 ms ± 15.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.25 ms ± 22.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [162]:
np.min(big_array)

3.7545111120085295e-07

In [163]:
np.max(big_array)

0.9999990651665599

In [164]:
big_array.min()

3.7545111120085295e-07

In [165]:
big_array.sum()

499921.2316513437

In [166]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [167]:
np.sum(X)

120

In [168]:
np.sum(X ,axis = 1)

array([ 6, 22, 38, 54])

In [169]:
np.sum(X ,axis = 0)

array([24, 28, 32, 36])

In [170]:
np.prod(X)

0

In [171]:
np.prod(X + 1)

2004189184

In [172]:
np.mean(X)

7.5

In [173]:
np.median(X)

7.5

In [174]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [175]:
np.median(v)

2.0

In [176]:
np.percentile(big_array, q = 50)

0.5004014017159111

In [177]:
np.median(big_array)

0.5004014017159111

In [178]:
np.percentile(big_array, q = 100)

0.9999990651665599

In [179]:
np.max(big_array)

0.9999990651665599

In [180]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q = percent))

3.7545111120085295e-07
0.2493415798055144
0.5004014017159111
0.7502867430880399
0.9999990651665599


In [181]:
np.var(big_array)

0.08347199726542333

In [182]:
np.std(big_array)

0.28891520774341967

In [183]:
x = np.random.normal(0, 1, size = 1000000)

In [184]:
np.mean(x)

0.000755464649744307

In [185]:
np.std(x)

0.9998784173460759

## 索引

In [186]:
np.min(x)

-5.060091583378058

In [187]:
np.argmin(x)

84705

In [188]:
x[720143]

-0.40912041482663525

In [189]:
np.argmax(x)

289853

In [190]:
x[693938]

0.6102928662798934

In [191]:
np.max(x)

5.110503281645443

## 排序和使用索引

In [192]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [193]:
np.random.shuffle(x)
x

array([ 9, 15,  7, 11,  4, 12,  0,  5,  6,  2, 13,  1,  8, 14, 10,  3])

In [194]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [195]:
x

array([ 9, 15,  7, 11,  4, 12,  0,  5,  6,  2, 13,  1,  8, 14, 10,  3])

In [196]:
x.sort()

In [197]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [198]:
X = np.random.randint(10, size = (4, 4))
X

array([[4, 0, 5, 8],
       [4, 5, 7, 2],
       [0, 6, 3, 0],
       [1, 0, 1, 6]])

In [199]:
np.sort(X)

array([[0, 4, 5, 8],
       [2, 4, 5, 7],
       [0, 0, 3, 6],
       [0, 1, 1, 6]])

In [200]:
np.sort(X, axis = 1)

array([[0, 4, 5, 8],
       [2, 4, 5, 7],
       [0, 0, 3, 6],
       [0, 1, 1, 6]])

In [201]:
np.sort(X, axis = 0)

array([[0, 0, 1, 0],
       [1, 0, 3, 2],
       [4, 5, 5, 6],
       [4, 6, 7, 8]])

In [202]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [203]:
np.random.shuffle(x)

In [204]:
x

array([11,  8,  2, 14,  5, 12, 13,  7,  0, 15,  4,  6,  9, 10,  3,  1])

In [205]:
np.argsort(x)

array([ 8, 15,  2, 14, 10,  4, 11,  7,  1, 12, 13,  0,  5,  6,  3,  9],
      dtype=int64)

In [206]:
np.partition(x, 3)

array([ 1,  0,  2,  3,  5,  6,  4,  7,  8, 15, 13, 12,  9, 10, 14, 11])

In [207]:
np.argpartition(x, 3)

array([15,  8,  2, 14,  4, 11, 10,  7,  1,  9,  6,  5, 12, 13,  3,  0],
      dtype=int64)

In [208]:
X

array([[4, 0, 5, 8],
       [4, 5, 7, 2],
       [0, 6, 3, 0],
       [1, 0, 1, 6]])

In [209]:
np.argsort(X, axis = 1)

array([[1, 0, 2, 3],
       [3, 0, 1, 2],
       [0, 3, 2, 1],
       [1, 0, 2, 3]], dtype=int64)

In [210]:
np.argpartition(X , 2, axis = 1)

array([[1, 0, 2, 3],
       [3, 0, 1, 2],
       [0, 3, 2, 1],
       [1, 0, 2, 3]], dtype=int64)

## Fancy Indexing

In [211]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [212]:
x[3]

3

In [213]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [214]:
x[3:9:2]

array([3, 5, 7])

In [215]:
[x[3],x[5],x[8]]

[3, 5, 8]

In [216]:
ind = [3, 5, 8]

In [217]:
x[ind]

array([3, 5, 8])

In [218]:
ind = np.array([[0, 2],
              [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [219]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [220]:
row = np.array([0, 1 ,2])
col = np.array([1, 2 ,3])
X[row, col]

array([ 1,  6, 11])

In [221]:
X[0, col]

array([1, 2, 3])

In [222]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [223]:
col = [True, False, True, True]

In [224]:
X[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

## numpy.array的比较

In [225]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [226]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [227]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [228]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [229]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [230]:
2 * x == 24- 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [231]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [232]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [233]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [234]:
np.sum(x <= 3)

4

In [235]:
np.count_nonzero(x <= 3)

4

In [236]:
np.any(x == 0)

True

In [237]:
np.any(x < 1)

True

In [238]:
np.all(x >= 0)

True

In [239]:
np.all(x > 0)

False

In [240]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [241]:
np.sum(X % 2 == 0)

8

In [242]:
np.sum(X % 2 == 0,axis = 1)

array([2, 2, 2, 2])

In [243]:
np.sum(X % 2 == 0,axis = 0)

array([4, 0, 4, 0])

In [244]:
np.all(X > 0,axis = 1)

array([False,  True,  True,  True])

In [245]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [246]:
np.sum((x > 3) & (x < 10))

6

In [247]:
np.sum((x > 3) && (x < 10))

SyntaxError: invalid syntax (<ipython-input-247-d834f65999a2>, line 1)

In [248]:
np.sum((x % 2 == 0) | (x > 10))

11

In [249]:
np.sum(~(x == 0))

15

In [250]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [251]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [252]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [253]:
X[X[:,3] % 3 == 0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])